-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 20:51:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CV19D
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CV19D` ;

-- -----------------------------------------------------
-- Schema CV19D
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CV19D` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `CV19D` ;

-- -----------------------------------------------------
-- Table `CV19D`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CV19D`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CV19D`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT(9) UNSIGNED NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CV19D`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CV19D`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CV19D`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT UNSIGNED NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(6,2) NOT NULL,
  `cus_total_sales` DECIMAL(6,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CV19D`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CV19D`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CV19D`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_petstore_idx` (`pst_id` ASC) VISIBLE,
  INDEX `fk_pet_customer1_idx` (`cus_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_petstore`
    FOREIGN KEY (`pst_id`)
    REFERENCES `CV19D`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_customer1`
    FOREIGN KEY (`cus_id`)
    REFERENCES `CV19D`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `CV19D`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `CV19D`;
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'dog store', '123 dog street', 'Miami', 'FL', 33150, 7869993838, 'dogstore@gmail.com', 'dogstoresite.com', 50000, 'notes1');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'cat store', '123 cat street', 'Tallahassee', 'FL', 32303, 4558231232, 'catstore@gmail.com', 'catsore.com', 45000, 'notes2');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'lizard store', '123 lizard street', 'Arcadia', 'FL', 23405, 2334456929, 'lizardstore@gmail.com', 'lizardstore.com', 65000, 'notes3');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'fox store', '123 fox street', 'Orlando ', 'FL', 13506, 7861234950, 'foxstore@gmail.com', 'foxstore.com', 60000, 'notes4');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'pig store', '2224 pig street', 'Manhattan', 'NY', 40506, 2234457182, 'pigstore@gmail.com', 'pigstore.com', 80000, 'notes5');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'tiger store', '2406 tiger street', 'London', 'UK', 30469, 2045591020, 'tigerstore@gmail.com', 'tigerstore.com', 55000, 'notes6');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'elephant store', '2405 elephant street', 'L.A', 'CA', 55040, 1145596812, 'elephantstore@gmail.com', 'elephantstore.com', 40000, 'notes7');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'penguin store', '9987 penguin street', 'Chicago', 'IL', 40294, 7728290281, 'penguinstore@gmail.com', 'penguinstore.com', 47000, 'notes8');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'bear store', '6234 bear street', 'Seattle', 'WA', 24959, 3374839203, 'bearstore@gmail.com', 'bearstore.com', 90000, 'notes9');
INSERT INTO `CV19D`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'lion store', '8982 lion street', 'Detroit', 'MI', 20459, 9872839401, 'lionstore@gmail.com', 'lionstore.com', 70000, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CV19D`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `CV19D`;
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'John', 'Doe', '4040 e street', 'FL', 54023, 2240501020, 'john@gmail.com', 1000, 2, 'notes1');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Elizabeth', 'frank', '2040 w street', 'NY', 40204, 2240412424, 'elizabeth@yahoo.com', 1230, 1, 'notes2');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Chris', 'Von', '6729 s street', 'WI', 29459, 6749124929, 'Chris@gmail.com', 200, 1, 'notes3');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sage ', 'Orozco', '8673 e street', 'FL', 24059, 2094581929, 'Sage@aol.com', 5000, 3, 'notes4');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Myles', 'Vargas', '2194 s street', 'MI', 79582, 6967032049, 'Myles@gmail.com', 0, 4, 'notes5');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Josephine', 'Carson', '3950 e street', 'NY', 58690, 4958239299, 'Josephine@gmail.com', 100, 2, 'notes6');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Kathy', 'Herrera', '2924 w street', 'WA', 68390, 2049568293, 'KathyH@yahoo.com', 5040, 6, 'notes7');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Giovani', 'Kayle', '0120 n street', 'NY', 20495, 2056093294, 'Giovani@gmail.com', 1000, 1, 'notes8');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Kathy', 'Wu', '778 n street', 'FL', 20459, 3956853829, 'Kathy@gmail.com', 2400, 2, 'notes9');
INSERT INTO `CV19D`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Yazmin', 'Fuller', '887 w street', 'NY', 50691, 2459548239, 'Yazmin@yahoo.com', 1000, 2, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CV19D`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `CV19D`;
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 3, 'Retreiver', 'm', 250, 300, 4, 'golden yellow', '2022-01-20', 'y', 'y', 'notes1');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 4, 'cat', 'f', 200, 400, 3, 'black', '2022-03-03', 'y', 'n', 'notes2');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 5, 'Calico-cat', 'm', 450, 300, 7, 'green', '2022-01-07', 'n', 'y', 'notes3');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 1, 'lion', 'm', 400, 250, 4, 'brown', '2022-01-10', 'y', 'y', 'notes4');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 2, 'fox', 'f', 500, 500, 2, 'red', '2022-01-15', 'y', 'y', 'notes5');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 3, 'otter', 'f', 245, 300, 1, 'grey', '2022-01-30', 'n', 'n', 'notes6');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 1, 'hippo', 'm', 200, 240, 6, 'white', '2022-02-01', 'n', 'n', 'notes7');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 1, 'rabbit', 'm', 500, 250, 2, 'blue', '2022-12-25', 'y', 'y', 'notes8');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 2, 'penguins', 'f', 600, 300, 8, 'black ', '2022-12-20', 'y', 'y', 'notes9');
INSERT INTO `CV19D`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 1, 'gekko', 'm', 250, 250, 2, 'green', '2022-11-08', 'y', 'y', 'notes10');

COMMIT;

