-- MySQL Script generated by MySQL Workbench
-- Wed Jan 25 20:23:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cv19d
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cv19d` ;

-- -----------------------------------------------------
-- Schema cv19d
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cv19d` DEFAULT CHARACTER SET utf8 ;
USE `cv19d` ;

-- -----------------------------------------------------
-- Table `cv19d`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`company` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`company` (
  'cmp_id' INT UNSIGNED NOT NULL AUTO_INCREMENT,
  'cmp_type' enum('C-Corp','S-Corp','Non-Profit-Corp','LLC','Partnership') NOT NULL,
  'cmp_street' VARCHAR(30) NOT NULL,
  'cmp_city' VARCHAR(20) NOT NULL,
  'cmp_state' CHAR(2) NOT NULL,
  'cmp_zip' CHAR(9) NOT NULL,
  'cmp_phone' BIGINT NOT NULL,
  'cmp_ytd_sales' DECIMAL(10,2) NOT NULL,
  'cmp_email' VARCHAR(100) NULL,
  'cmp_url' VARCHAR(100) NULL,
  'cmp_notes' VARCHAR(255) NULL,
  PRIMARY KEY (`cmp_id`))
ENGINE = InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

SHOW WARNINGS;

INSERT INTO company
VALUES
()


-- -----------------------------------------------------
-- Table `cv19d`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.'customer' ;

CREATE TABLE IF NOT EXISTS `cv19d`.'customer' (
  `cus_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cmp_id` INT UNSIGNED NOT NULL,
  `cus_ssn` binary(64) NOT NULL,
  `cus_salt` binary(64) NOT NULL,
  `cus_type` enum('Loyal','Discount','Impulse','Need-based','Wandering') NULL,
  `cus_first` Varchar(15) NOT NULL,
  `cus_last` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` CHAR(9) NOT NULL,
  `cus_phone` BIGINT NOT NULL,
  `cus_email` VARCHAR(100) NULL,
  'cus_balance' decimal(7,2),
  'cus_tot_sales' decimal(7,2),
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`),
  UNIQUE INDEX `ux_cus_ssn` (`cus_ssn` ASC),
  CONSTRAINT `fk_customer_company`
    FOREIGN KEY (`cmp_id`)
    REFERENCES `cv19d`.`company` (`cmp_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv19d`.`dependent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`dependent` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`dependent` (
  `dep_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NOT NULL,
  `dep_added` DATE NOT NULL,
  `dep_ssn` CHAR(9) NOT NULL,
  `dep_fname` VARCHAR(15) NOT NULL,
  `dep_lname` VARCHAR(30) NOT NULL,
  `dep_dob` DATE NOT NULL,
  `dep_relation` VARCHAR(20) NOT NULL,
  `dep_street` VARCHAR(30) NOT NULL,
  `dep_city` VARCHAR(20) NOT NULL,
  `dep_state` CHAR(2) NOT NULL,
  `dep_zip` CHAR(9) NOT NULL,
  `dep_phone` BIGINT NOT NULL,
  `dep_email` VARCHAR(100) NULL,
  `dep_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`dep_id`),
  INDEX `fk_dependent_employee_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_dependent_employee`
    FOREIGN KEY (`emp_id`)
    REFERENCES `cv19d`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv19d`.`emp_hist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`emp_hist` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`emp_hist` (
  `eht_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NULL,
  `eht_date` DATETIME NOT NULL,
  `eht_type` ENUM('i', 'u', 'd') NOT NULL,
  `eht_job_id` TINYINT NOT NULL,
  `eht_emp_salary` DECIMAL(8,2) NOT NULL,
  `eht_usr_changed` VARCHAR(30) NOT NULL,
  `eht_reason` VARCHAR(45) NOT NULL,
  `eht_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`eht_id`),
  INDEX `fk_emp_hist_employee1_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_emp_hist_employee1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `cv19d`.`employee` (`emp_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv19d`.`benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`benefit` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`benefit` (
  `ben_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ben_name` VARCHAR(45) NOT NULL,
  `ben_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`ben_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv19d`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`plan` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`plan` (
  `pln_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NOT NULL,
  `ben_id` TINYINT UNSIGNED NOT NULL,
  `pln_type` ENUM('single', 'spouse', 'family') NOT NULL,
  `pln_cost` DECIMAL(6,2) NOT NULL,
  `pln_election_date` DATE NOT NULL,
  `pln_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pln_id`),
  INDEX `fk_plan_employee1_idx` (`emp_id` ASC) VISIBLE,
  INDEX `fk_plan_benefit1_idx` (`ben_id` ASC) VISIBLE,
  CONSTRAINT `fk_plan_employee1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `cv19d`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_benefit1`
    FOREIGN KEY (`ben_id`)
    REFERENCES `cv19d`.`benefit` (`ben_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cv19d`.`job`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'secretary', NULL);
INSERT INTO `cv19d`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'service tech', NULL);
INSERT INTO `cv19d`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'manager', NULL);
INSERT INTO `cv19d`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'cashier', NULL);
INSERT INTO `cv19d`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'janitor', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cv19d`.`employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 4, '000222333', 'marsha', 'fromm', '1978-03-09', '2003-05-16', NULL, 50000, '2222 s street', 'Miami', 'FL', '33150', 2223339994, 'marsha@gmail.com', NULL);
INSERT INTO `cv19d`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 3, '223441234', 'steve', 'crenshie', '1990-09-30', '1980-09-24', NULL, 60000, '423 e street', 'Miami', 'FL', '24059', 1239431238, 'stevec@gmail.com', NULL);
INSERT INTO `cv19d`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 2, '994321321', 'kelsey', 'roberts', '2000-04-25', '2010-01-25', NULL, 65000, '4321 n monroe st', 'Miami', 'FL', '49512', 4951924959, 'kelseyg@gmail.com', NULL);
INSERT INTO `cv19d`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 3, '695483123', 'robert', 'laurie', '2001-05-05', '1998-01-03', NULL, 90000, '249 w street', 'Orlando', 'FL', '49421', 4959321942, 'robert2@gmail.com', NULL);
INSERT INTO `cv19d`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 1, 'kathy', 'cameron', 'dobb', '1995-01-25', '2010-02-18', NULL, 85000, '112 nw street', 'Tampa', 'FL', '20249', 2994124592, 'kathy@gmail.com', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cv19d`.`dependent`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 1, '2004-05-18', '412323223', 'Billy', 'bob', '1964-12-14', 'husband', '223 e st', 'Miami', 'FL', '33941', 2223941239, 'billybob@gmail.com', NULL);
INSERT INTO `cv19d`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 2, '2006-10-20', '558321234', 'Bobby', 'Sue', '1990-10-28', 'wife', '2491 s street', 'Miami', 'FL', '24912', 4951283840, 'Bsue@gmail.com', NULL);
INSERT INTO `cv19d`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 3, '2001-05-25', '285923823', 'Mary', 'Blue', '2001-04-25', 'daughter', '938 n street', 'Tampa', 'FL', '85412', 9584281394, 'mblue@gmail.com', NULL);
INSERT INTO `cv19d`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 4, '2005-01-01', '495832142', 'Bart', 'Simpson', '2005-04-20', 'son', '5954 nw street', 'Orlando', 'FL', '95842', 9584281929, 'bartsimpson@yahoo.com', NULL);
INSERT INTO `cv19d`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 5, '2015-06-30', '599584821', 'John', 'Doe', '2021-01-01', 'son', '948 commons ave', 'Tampa', 'FL', '29458', 9581284958, 'Jdoe@gmail.com', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cv19d`.`emp_hist`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 1, '2001-03-19 09:30:00', 'i', 1, 50000, 'test', 'promotion', NULL);
INSERT INTO `cv19d`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 2, '2003-05-10 10:45:00', 'u', 2, 75000, 'test', 'demotion', NULL);
INSERT INTO `cv19d`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 3, '2005-07-18 12:00:00', 'i', 4, 50000, 'test', 'promotion', NULL);
INSERT INTO `cv19d`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 4, '2013-10-31 05:30:00', 'i', 1, 60000, 'test', 'demotion', NULL);
INSERT INTO `cv19d`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 5, '2017-05-19 11:00:00', 'u', 2, 85000, 'test', 'promotion', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cv19d`.`benefit`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'medical', NULL);
INSERT INTO `cv19d`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'dental', NULL);
INSERT INTO `cv19d`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'long-term disability', NULL);
INSERT INTO `cv19d`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, '401k', NULL);
INSERT INTO `cv19d`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'vision', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cv19d`.`plan`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 1, 2, 'single', 500, '2013-01-01', NULL);
INSERT INTO `cv19d`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 2, 3, 'spouse', 1000, '2012-05-24', NULL);
INSERT INTO `cv19d`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 3, 4, 'family', 1500, '2014-05-15', NULL);
INSERT INTO `cv19d`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 4, 1, 'spouse', 800, '2014-08-01', NULL);
INSERT INTO `cv19d`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 5, 2, 'family', 600, '2010-10-10', NULL);

COMMIT;

