-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 13:59:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cv19d
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cv19d` ;

-- -----------------------------------------------------
-- Schema cv19d
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cv19d` DEFAULT CHARACTER SET utf8 ;
USE `cv19d` ;

-- -----------------------------------------------------
-- Table `cv19d`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`petstore` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` CHAR(9) NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv19d`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`customer` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` CHAR(9) NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv19d`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cv19d`.`pet` ;

CREATE TABLE IF NOT EXISTS `cv19d`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_petstore_idx` (`pst_id` ASC) VISIBLE,
  INDEX `fk_pet_customer1_idx` (`cus_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_petstore`
    FOREIGN KEY (`pst_id`)
    REFERENCES `cv19d`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_customer1`
    FOREIGN KEY (`cus_id`)
    REFERENCES `cv19d`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cv19d`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'claws and paws', '123 main st', 'L.A.', 'CA', '32303', 1112223334, 'clawsandpaws@gmail.com', 'clawsandpaws.com', 50000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'furry friends', '1435 chase dr', 'Chicago', 'IL', '23049', 2223334451, 'furryfriends@gmail.com', 'furryfriends.com', 45000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'pet partners', '811 4th st', 'NY', 'NY', '39230', 1234567952, 'petpartners@gmail.com', 'petpartners.com', 60000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'pet palace', '1111 tennesee st', 'Tallahassee', 'FL', '33142', 2330403220, 'ppalace@gmail.com', 'petpalace.com', 70000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'purrs and grrs', '751 lois lane', 'Phoenix', 'AZ', '23230', 4492304921, 'purrsandgrrs@yahoo.com', 'purrsandgurrs.com', 65000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'parrotsforsale', '125 E st.', 'Miami', 'FL', '42394', 4950232192, 'parrotsforsale@msn.com', 'parrotsforsale.com', 30000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'dogsforsale', '555 lucky st', 'Orlando', 'FL', '33219', 4738293817, 'dogsforsale@outlook.com', 'dogsforsale.com', 90000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'lizardsforsale', '892 S st', 'Atlanta', 'GA', '89212', 5854828321, 'lizardsforsale@myspace.com', 'lizardsforsale.com', 78000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'catvendors', '2223 4th ave', 'Hartford', 'CT', '29348', 4832913845, 'catvendors@yahoo.com', 'catvendors.com', 75000, NULL);
INSERT INTO `cv19d`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Hamsterworld', '348 9th ave', 'Miami', 'FL', '33150', 3052234821, 'hamsterworld@gmail.com', 'hamsterworld.com', 50000, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cv19d`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Billy', 'Bob', '502 Shady Dr.', 'Minneapolis', 'MN', '43203', 6123942312, 'billybob@msn.com', 139.52, 1000, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Bobby', 'Sue', '195 rutherford cir.', 'Charleston', 'WV', '95234', 4954824921, 'BSue@yahoo.com', 50, 1356.89, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Stevie', 'Ray', '8624 Band drive', 'Panama City Beach', 'FL', '42934', 4059231234, 'Sray@gmail.com', 9.34, 567.63, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Felicia', 'Fuller', '7831 T Lane', 'Sturgis', 'SD', '12492', 9528423342, 'FeliciaFuller@outlook.com', 0.0, 784.29, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Victoria', 'Valis', '2373 Northshore Dr.', 'Laramie', 'WY', '23492', 2059238429, 'VictoriaV@gmail.com', 1189.32, 19456.78, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Kai', 'Cenat', '102 Ny drive', 'Ny', 'NY', '58428', 5963021234, 'Kaicenat@twitch.com', 10, 200.10, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Felix', 'xqc', '1293 S drive', 'Austin', 'TX', '53245', 4950392129, 'Xqc@yahoo.com', 42.59, 110.30, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Grant', 'Herbo', '2348 Sw Hill', 'Chicago', 'IL', '30532', 1234950212, 'Gherbo@gmail.com', 60.69, 1010.50, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Eduardo', 'Hitch', '6970 H drive', 'Juno', 'AL', '69783', 6948293042, 'Ehitch@msn.com', 0.0, 250, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Clint', 'Stevens', '968 E Rising st', 'Miami', 'FL', '33123', 5864928349, 'ClintS@Aol.com', 0.0, 500, NULL);
INSERT INTO `cv19d`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Chris', 'Chan', '5968 W st', 'Las Vegas', 'NV', '96049', 9604928421, 'chrischan@yahoo.com', 150.50, 444.20, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cv19d`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `cv19d`;
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 1, 'Doberman', 'm', 360, 520, 52, 'black', '2009-07-05', 'y', 'y', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 2, 'Chiwawa', 'f', 200, 400, 10, 'brown', '2010-10-10', 'n', 'y', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 3, 'Calico Cat', 'M', 500, 1000, 2, 'black/white', '2015-05-15', 'y', 'y', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 4, 'Komodo Dragon', 'm', 600, 750, 1, 'green', '2023-01-01', 'y', 'y', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 5, 'Hamster', 'm', 50, 200, 4, 'light brown', '2012-02-25', 'y', 'y', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 6, 'Golden Retreiver', 'f', 450, 600, 10, 'golden brown', '2016-09-10', 'y', 'y', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 7, 'German Shepard', 'f', 300, 505, 3, 'black/brown', '2017-10-10', 'y', 'y', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 8, 'parrot', 'm', 200, 500, 2, 'green', '2020-02-20', 'y', 'n', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 9, 'Snake', 'f', 1000, 1500, 5, 'Green/black', '2010-06-20', 'y', 'n', NULL);
INSERT INTO `cv19d`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 10, 'Hamster', 'm', 200, 500, 1, 'black', '2008-11-08', 'y', 'y', NULL);

COMMIT;

